resolver: lts-6.2

packages:
- google-shim
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-queue
- tensorflow-nn
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test

extra-deps:
# proto-lens is not yet in Stackage.
- proto-lens-0.1.0.5
- proto-lens-protoc-0.1.0.5
- proto-lens-descriptors-0.1.0.5
- snappy-framing-0.1.1
- snappy-0.2.0.2

# Allow our custom Setup.hs scripts to import Data.ProtoLens.Setup from the version of
# `proto-lens-protoc` in stack's local DB.  See:
# https://github.com/google/proto-lens/blob/master/README.md#using-cabal
explicit-setup-deps:
  "*": true

# For Mac OS X, whose linker doesn't use this path by default:
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include
