resolver: lts-11.9

packages:
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test

extra-deps:
- snappy-framing-0.1.1
- snappy-0.2.0.2
- proto-lens-protobuf-types-0.3.0.1
- proto-lens-protoc-0.3.1.0
- proto-lens-0.3.1.0
- lens-labels-0.2.0.1

# For Mac OS X, whose linker doesn't use this path by default
# unless you run `xcode-select --install`.
# TODO: remove this once we stop depending on `snappy`.
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include

nix:
    enable: false
    shell-file: shell.nix
