resolver: lts-16.18

packages:
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test

extra-deps:
- snappy-framing-0.1.2
- snappy-0.2.0.2

# For Mac OS X, whose linker doesn't use this path by default
# unless you run `xcode-select --install`.
# TODO: remove this once we stop depending on `snappy`.
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include

docker:
    enable: false
    image: tensorflow/haskell:2.3.0

nix:
    enable: false
    # nixos-21.05 with libtensorflow 2.3.0
    path: ["nixpkgs=https://github.com/NixOS/nixpkgs/archive/c7cb72b0cae397d311236d6773338efb4bd4f2d1.tar.gz"]
    packages: [snappy, zlib, protobuf, python3Packages.tensorflow_2.libtensorflow]
