resolver: lts-8.13

packages:
- google-shim
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-queue
- tensorflow-nn
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test

extra-deps:
- snappy-framing-0.1.1
- snappy-0.2.0.2

# For Mac OS X, whose linker doesn't use this path by default:
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include
