resolver: lts-16.18

packages:
- tensorflow
- tensorflow-core-ops
- tensorflow-logging
- tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
- tensorflow-mnist
- tensorflow-mnist-input-data
- tensorflow-records
- tensorflow-records-conduit
- tensorflow-test

extra-deps:
- c2hs-0.28.8
- language-c-0.9.2
- snappy-0.2.0.2
- snappy-framing-0.1.2

# For Mac OS X, whose linker doesn't use this path by default
# unless you run `xcode-select --install`.
# TODO: remove this once we stop depending on `snappy`.
extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include

docker:
    enable: false
    image: tensorflow/haskell:2.12.0

nix:
    enable: false
    # nixos-22.11 with libtensorflow 2.10.1
    path: ["nixpkgs=https://github.com/NixOS/nixpkgs/archive/2dea8991d89b9f1e78d874945f78ca15f6954289.tar.gz"]
    packages: [snappy, zlib, protobuf, libtensorflow]
